import Table from '@/app/views/job/Table'
import Create from "@/app/views/job/create";
import Head from "next/head";

export default function Home() {
  return (
    <section data-theme="cupcake">
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Proptilla Job Schedules
        </h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <Create />
        </div>

        {/* table */}
        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </section>
  );
}
