import Table from '@/app/views/job/Table'
import Create from "@/app/views/job/Create";
import Head from "next/head";

export default function Home() {

  return (
      <section data-theme="cupcake">
          <Head>
              <title>CRUD Application</title>
              <meta name="description" content="Generated by create next app"/>
              <link rel="icon" href="/favicon.ico"/>
          </Head>

          <main className="m-auto py-5 px-10">
              <h1 className="text-xl md:text-5xl text-center font-bold py-10">
                  Proptilla Job Schedules
              </h1>

              <div className="m-auto flex justify-center py-5 border-b">
                  <span>URL :&nbsp;</span><p>{process.env.NEXT_PUBLIC_API_URL}</p>
              </div>

              <div className="m-auto flex justify-between py-5">
                  <Create/>
              </div>

              <div className="m-auto"><Table/></div>
          </main>
    </section>
  );
}
